const GLOSSARY = [
{term:"ADS1299", en:"TI ADS1299", cat:"芯片", py:"A",
 desc:"德州仪器(TI)专为EEG设计的8通道24位ΔΣ ADC，含PGA(1-24x可编程增益)、偏置驱动(BIAS)、右腿驱动(DRL)、Lead-off检测。输入参考噪声<1μVpp，输入阻抗2GΩ——BCI模拟前端的设计标杆。"},
{term:"AFE", en:"Analog Front End", cat:"硬件", py:"A",
 desc:"模拟前端。在BCI中指电极信号的第一级处理电路：仪表放大器(INA)→PGA→抗混叠滤波→ADC。好的AFE设计直接决定了BCI系统信号质量的下限。"},
{term:"ADC", en:"Analog-to-Digital Converter", cat:"硬件", py:"A",
 desc:"模数转换器。BCI中关键参数：分辨率(≥16bit)、采样率(EEG≥250Hz, Spike≥20kHz)、ENOB(有效位数，比标称分辨率低1-3bit)、输入参考噪声(<1μVpp)。ΔΣ ADC因其高分辨率和内置数字滤波成为BCI的主流选择。"},
{term:"BLE", en:"Bluetooth Low Energy", cat:"通信", py:"B",
 desc:"低功耗蓝牙。BCI无线传输的主流方案：nRF52840/nRF5340(北欧半导体)是旗舰SoC。关键参数：最小连接间隔7.5ms、MTU最大247字节、PHY速率1M/2Mbps。植入式可通过皮肤传输（<2cm深度）。"},
{term:"BCI", en:"Brain-Computer Interface", cat:"概念", py:"B",
 desc:"脑机接口。在大脑与外部设备之间建立直接通信通道的技术。按植入方式分：非侵入式(头皮EEG)、半侵入式(ECoG硬膜下/硬膜外)、侵入式(皮层植入)。按信号类型分：Spike(单神经元放电)、LFP(局部场电位)、ECoG(皮层电图)、EEG(头皮脑电)。"},
{term:"Blindsight", en:"Neuralink Blindsight", cat:"产品", py:"B",
 desc:"Neuralink的视觉恢复BCI系统。外置摄像头→实时视觉处理引擎→电刺激模式生成器→视觉皮层微电极阵列→患者"看到"低分辨率视觉图像。已获FDA"突破性设备认定"，临床前测试阶段。目标：先实现导航级视觉，最终超人视觉(红外/紫外/夜视)。"},
{term:"CMSIS-DSP", en:"Cortex Microcontroller Software Interface Standard - DSP", cat:"软件", py:"C",
 desc:"ARM官方DSP库，为Cortex-M处理器提供优化的信号处理函数：FFT(arm_rfft_fast_f32)、FIR/IIR滤波、矩阵运算、统计函数。在M4/M7上比手写汇编快3-5倍，是嵌入式BCI信号处理的核心工具。"},
{term:"CMSIS-NN", en:"CMSIS Neural Network", cat:"软件", py:"C",
 desc:"ARM官方神经网络推理库，为Cortex-M提供优化的卷积/池化/全连接层。支持INT8量化推理，配合TFLite Micro使用。在Cortex-M4/M7上推理速度比朴素实现快4-5倍。"},
{term:"CSP", en:"Common Spatial Pattern", cat:"算法", py:"C",
 desc:"共同空间模式——运动想象BCI最经典的特征提取算法。通过最大化两类信号的方差比来寻找最优空间滤波器。本质是一个广义特征值分解问题。CSP+LDA是MI-BCI的经典基线(≈65-75%准确率)。FBCSP(滤波组CSP)是增强版。"},
{term:"CMRR", en:"Common Mode Rejection Ratio", cat:"硬件", py:"C",
 desc:"共模抑制比——衡量差分放大器抑制共模信号(如50Hz工频干扰)的能力。ADS1299的CMRR>110dB，意味着共模信号被抑制10万倍以上。右腿驱动(DRL)可进一步提升CMRR至120dB+。"},
{term:"ΔΣ ADC", en:"Delta-Sigma ADC", cat:"硬件", py:"D",
 desc:"ΔΣ模数转换器——BCI中ADC的主流架构。通过过采样(实际采样率>>Nyquist)、噪声整形(将量化噪声推向高频)、数字抽取滤波实现24bit高分辨率。ADS1299是ΔΣ ADC在BCI中的典型应用。"},
{term:"DMA", en:"Direct Memory Access", cat:"嵌入式", py:"D",
 desc:"直接存储器访问——无需CPU参与的外设-to-内存数据传输。BCI中DMA双缓冲是标配：Buffer A采集时，CPU处理Buffer B→交替切换→零数据丢失。配置要点：DMA半完成中断(HT)和完成中断(TC)。"},
{term:"DRL", en:"Driven Right Leg", cat:"硬件", py:"D",
 desc:"右腿驱动——通过将人体共模信号经反相放大后反馈回人体(通过DRL电极)，形成负反馈环路，抑制共模噪声。ADS1299内置CMS(共模采样)+DRL，可将CMRR从60dB提升至110dB+。是EEG采集中对抗50Hz工频干扰最关键的硬件手段。"},
{term:"ECoG", en:"Electrocorticography", cat:"概念", py:"E",
 desc:"皮层电图——将电极置于大脑皮层表面(硬膜下或硬膜外)记录的脑电信号。幅值50-500μV，频率范围0.5-200Hz。信号质量介于EEG(头皮)和spike(皮层内)之间，SNR=10-100x，被认为是BCI的"最佳性价比"位置。"},
{term:"EEG", en:"Electroencephalography", cat:"概念", py:"E",
 desc:"头皮脑电图——通过置于头皮表面的电极记录的大脑电活动。是非侵入式BCI的主要信号来源。幅值1-100μV峰值(典型10-50μV)，频率范围0.5-100Hz。主要频段：δ(0.5-4Hz)、θ(4-8Hz)、α(8-13Hz)、β(13-30Hz)、γ(30-100Hz)。"},
{term:"EEGNet", en:"EEGNet", cat:"算法", py:"E",
 desc:"Lawhern等人2018年提出的紧凑CNN架构，专为EEG分类设计。核心设计：时间卷积(提取ERP模式)+深度可分离卷积(空间滤波，等价于CSP的神经网络版)+逐点卷积(特征融合)+全局平均池化。总共约6000参数，INT8量化后<12KB，推理<500μs @STM32F4。BCI嵌入式推理的事实标准。"},
{term:"EMG", en:"Electromyography", cat:"概念", py:"E",
 desc:"肌电图——肌肉纤维动作电位。在非侵入式BCI中EMG是主要伪迹源之一(幅值10-500μV，频率20-500Hz)。多模态BCI中EMG作为辅助通道(与EEG融合)。"},
{term:"EOG", en:"Electrooculography", cat:"概念", py:"E",
 desc:"眼电图——眼球运动(角膜-视网膜电势差)产生的信号。幅值50-5000μV，是EEG的100倍！主要集中在<10Hz的前额电极(Fp1/Fp2)。ICA可以分离去除眼电成分。"},
{term:"ERD/ERS", en:"Event-Related Desynchronization/Synchronization", cat:"概念", py:"E",
 desc:"事件相关去同步/同步——运动想象时，对侧运动皮层的μ节律(8-12Hz)和β节律(13-30Hz)功率下降(ERD)，随后恢复甚至增强(ERS)。这是运动想象BCI最核心的神经生理基础。"},
{term:"FPGA", en:"Field-Programmable Gate Array", cat:"硬件", py:"F",
 desc:"现场可编程门阵列——用于高速信号处理的硬件平台。在BCI中用于：实时spike排序、多通道并行滤波、ADC数据直通处理(<1μs延迟)。Xilinx Zynq(ARM+FPGA)是BCI FPGA的主流选择。"},
{term:"FreeRTOS", en:"FreeRTOS", cat:"软件", py:"F",
 desc:"开源实时操作系统，ARM Cortex-M上最流行的RTOS。BCI中用于管理多任务：采集Task(最高优先级，250Hz)→处理Task(FFT/CSP)→BLE Tx Task→UI Task→电源管理Task。栈溢出检测(uxTaskGetStackHighWaterMark)是BCI固件开发的必须检查项。"},
{term:"ICA", en:"Independent Component Analysis", cat:"算法", py:"I",
 desc:"独立分量分析——盲源分离算法，在BCI中主要用于去除眼电(EOG)、心电(ECG)、肌电(EMG)等伪迹。嵌入式策略：离线计算ICA分量矩阵(8ch×8分量=256B)→在线投影(矩阵乘法，<10μs)。"},
{term:"Intan RHD2000", en:"Intan RHD2000 Series", cat:"芯片", py:"I",
 desc:"Intan Technologies的16-64通道神经信号放大器芯片系列。内置16bit ADC，0.6mW/32ch超低功耗，采样率可达30kHz/ch。在侵入式BCI中广泛使用。RHD2164(64通道)和RHS2116(16通道刺激+记录)是旗舰型号。"},
{term:"LFP", en:"Local Field Potential", cat:"概念", py:"L",
 desc:"局部场电位——电极附近数百个神经元的突触后电位总和。幅值100-1000μV，频率0.5-200Hz。包含比spike更宏观的神经活动信息。LFP频段可自动判断用户睡眠/清醒状态→芯片自动休眠/唤醒。"},
{term:"MNE-Python", en:"MNE-Python", cat:"软件", py:"M",
 desc:"Python EEG/MEG分析库，BCI数据处理的事实标准。核心功能：数据加载(EDF/BrainVision格式)、预处理(滤波/ICA/降采样)、时频分析、源定位。版本1.8(2025)，推荐BCI入门必装。"},
{term:"MOABB", en:"Mother Of All BCI Benchmarks", cat:"软件", py:"M",
 desc:"BCI基准测试框架(NeuroTechX)。提供标准数据集(BCI Competition IV等)、统一评估协议、跨受试者评估流程。一行代码即可复现经典算法并得到标准分数。GitHub: NeuroTechX/moabb"},
{term:"Muse 2", en:"Muse 2 (Interaxon)", cat:"产品", py:"M",
 desc:"Interaxon的消费级EEG头环，4通道(TP9/AF7/AF8/TP10)+加速度计+陀螺仪。干电极，即开即用，¥1800。Python SDK可用(muselsl)，是体验BCI性价比最高的硬件选择。"},
{term:"Neuralink N1", en:"Neuralink N1", cat:"产品", py:"N",
 desc:"Neuralink的第一代侵入式BCI芯片，2024年首例人体植入。1024通道(64根threads×16电极)，10bit ADC，硬件spike检测，NFC+BLE双模无线。第4代(2026)由三星4nm代工，升级为双向通信(读取+刺激)。"},
{term:"nRF52840", en:"Nordic nRF52840", cat:"芯片", py:"N",
 desc:"Nordic半导体BLE旗舰SoC：Cortex-M4F@64MHz，1MB Flash+256KB RAM，BLE 5.3。BCI无线传输的首选方案。开发套件nRF52840 DK约¥150-200。"},
{term:"OpenBCI", en:"OpenBCI", cat:"产品", py:"O",
 desc:"全球最大的开源BCI平台。主要产品：Cyton(8ch ADS1299+PIC32MX,¥3600)、Ganglion(4ch低功耗,¥2500)、Cyton+Daisy(16ch,¥5800)。固件开源(Arduino兼容)，Python SDK完善。学习BCI的最佳开源参考。"},
{term:"OTA", en:"Over-The-Air", cat:"嵌入式", py:"O",
 desc:"空中固件升级。BCI设备(特别是植入式)必须支持OTA：双分区Bank A/B→下载到备分区→CRC校验→切换启动标志→复位→异常回滚。Neuralink已实现类似特斯拉式的OTA固件升级。"},
{term:"PGA", en:"Programmable Gain Amplifier", cat:"硬件", py:"P",
 desc:"可编程增益放大器——ADC输入的前置放大器。ADS1299的PGA支持1/2/4/6/8/12/24倍增益。增益选择原则：根据信号幅值和ADC量程匹配，PGA过高会同时放大信号和噪声，SNR不一定改善。"},
{term:"PSD", en:"Power Spectral Density", cat:"算法", py:"P",
 desc:"功率谱密度——信号功率在频率域的分布。BCI中最基础的频域分析：用Welch方法(分段+加窗+FFT+平均)计算，识别α峰(10Hz)/β峰(20Hz)是EEG分析的"Hello World"。"},
{term:"P300", en:"P300 Event-Related Potential", cat:"概念", py:"P",
 desc:"事件相关电位P300——小概率刺激出现后约300ms在顶叶出现的正电位。是BCI拼写器(字符输入)最常用的范式。经典P300拼写器准确率可达95%+，但速度较慢(约1字符/秒)。"},
{term:"RTOS", en:"Real-Time Operating System", cat:"软件", py:"R",
 desc:"实时操作系统——保证关键任务在规定时间内完成。BCI中使用FreeRTOS或μT-Kernel。任务优先级：采集Task(最高，中断驱动)>处理Task(中等)>通信Task(低)。不按时完成采集→丢数据→分类准确率断崖下降。"},
{term:"SNR", en:"Signal-to-Noise Ratio", cat:"概念", py:"S",
 desc:"信噪比。在BCI中通常用dB表示：SNR=10·log₁₀(P_signal/P_noise)。头皮EEG运动想象SNR约2-10x(3-10dB)，ECoG约10-100x(10-20dB)，侵入式spike约5-50x(7-17dB)。SNR<1时需要多次平均或强先验。"},
{term:"Spike", en:"Spike (Neural)", cat:"概念", py:"S",
 desc:"单神经元动作电位——侵入式BCI的核心信号。幅值10-500μV(近距离)，持续时间约1ms，放电率1-100Hz。需要在硬件级别实时检测(模拟比较器+阈值)，软件级别做spike排序(PCA+K-means)。"},
{term:"SSVEP", en:"Steady-State Visually Evoked Potential", cat:"概念", py:"S",
 desc:"稳态视觉诱发电位——注视特定频率闪烁的视觉刺激时，枕叶EEG中出现与刺激频率相同的振荡。BCI实现：多目标用不同频率→检测EEG中最强的SSVEP频率→确定目标。速度最快(可达60+目标/分钟)、准确率最高(95%+)的BCI范式。"},
{term:"STM32F407", en:"STM32F407", cat:"芯片", py:"S",
 desc:"意法半导体Cortex-M4F MCU：168MHz，FPU+DSP指令，192KB RAM+1MB Flash。BCI嵌入式开发最常用的处理器。配合CMSIS-DSP可实现1024点FFT<2ms，跑TFLite Micro EEHGNet推理<500μs。"},
{term:"Spectral Transformer", en:"Spectral Transformer", cat:"算法", py:"S",
 desc:"马德里理工2026年发表的运动想象BCI方法。利用注意力机制处理EEG频谱特征，2分类运动想象准确率93.5%（当前最高）。参数量约20K→INT8后<40KB→可部署到Cortex-M55+Ethos-U55。"},
{term:"TFLite Micro", en:"TensorFlow Lite for Microcontrollers", cat:"软件", py:"T",
 desc:"TensorFlow针对微控制器的推理框架。BCI工作流：Python训练→TFLite转换→Post-training INT8量化→xxd转C数组→MCU推理。关键配置：arena_size(内存池，通常20-50KB)、OpResolver(只注册需要的算子)。"},
{term:"TrustZone", en:"ARM TrustZone", cat:"安全", py:"T",
 desc:"ARM TrustZone-M(ARMv8-M)——在单核MCU上创建安全分区和非安全分区。BCI安全应用：将加解密密钥、生物特征数据、固件完整性检查放在安全区(TrustZone Secure)，应用逻辑放在非安全区。"},
{term:"博睿康 NEO", en:"Neuro Care NEO", cat:"产品", py:"B",
 desc:"博睿康(中国)的侵入式BCI系统，全球首个获得注册证的侵入式BCI产品(NMPA 2026.03.13)。128通道硬膜外电极，解码运动意图控制气动手套。36例临床手术，术后3月响应率100%。2025年营收1.08亿元(首破亿)。"},
{term:"干电极", en:"Dry Electrode", cat:"硬件", py:"G",
 desc:"无需导电膏的EEG电极。靠金属针(不锈钢/金)或导电橡胶直接接触头皮。接触阻抗20-200kΩ(湿电极<5kΩ)，需要AFE输入阻抗>1GΩ。佩戴时间从30分钟缩至1-5分钟，信号质量略差(但可用性大幅提升)。Muse 2已成功使用干电极。"},
{term:"湿电极", en:"Wet Electrode (Ag/AgCl)", cat:"硬件", py:"S",
 desc:"银/氯化银电极+导电膏——EEG的金标准。接触阻抗<5kΩ，信号质量最佳。缺点：佩戴需要准备时间(涂导电膏约30分钟)、电极膏会干(2-8小时寿命)、可能引起皮肤过敏。"},
{term:"右腿驱动", en:"Driven Right Leg (DRL)", cat:"硬件", py:"Y",
 desc:"参见DRL词条。通过负反馈抑制人体共模噪声的电路技术，是EEG采集中对抗50Hz工频干扰最核心的硬件手段。"},
{term:"运动想象", en:"Motor Imagery (MI)", cat:"概念", py:"Y",
 desc:"运动想象——在脑海中想象肢体运动但不实际执行的BCI范式。想象左手运动→右侧运动皮层μ节律减弱(ERD)；想象右手→左侧减弱。MI-BCI竞赛(BCI Competition IV-2a)是评估BCI算法性能的标准基准。"},
{term:"硬膜外植入", en:"Epidural Implant", cat:"概念", py:"Y",
 desc:"将电极置于硬脑膜外(硬膜和颅骨之间)，不穿透硬膜和脑组织。相比皮层植入更安全，但信号略弱(隔了一层硬膜)。博睿康NEO采用此路线，是首个获批的侵入式BCI。"},
{term:"皮层植入", en:"Intracortical Implant", cat:"概念", py:"P",
 desc:"将微电极阵列直接插入大脑皮层组织中。信号质量最高(直接记录spike和LFP)，但需要手术穿透脑组织。Neuralink的Telepathy和Blindsight都采用此路线。"},
{term:"柔性电极", en:"Flexible Electrode", cat:"硬件", py:"R",
 desc:"使用柔性聚合物(而非刚性硅/金属)制成的电极。2026年北京脑科学研究所/智冉医疗在Nature发表可拉伸柔性电极，1024通道，随呼吸摆动不会断连。是侵入式BCI长期可靠性的关键突破。"},
{term:"神经反馈", en:"Neurofeedback", cat:"概念", py:"S",
 desc:"将脑电特征（如α波功率）实时反馈给用户（如LED亮度/声音频率），让用户学习自我调节脑电活动。是闭环BCI的最简单形式，也是BCI新手的第一个闭环项目。"},
{term:"工频干扰", en:"Power Line Interference", cat:"概念", py:"G",
 desc:"50Hz(中国)/60Hz(美国)交流电网辐射的电磁干扰，在EEG中幅值可达10-1000μV(是EEG信号的10-100倍)。对策：硬件DRL+屏蔽+软件50Hz陷波FIR滤波器。"},
{term:"眼电伪迹", en:"Ocular Artifact", cat:"概念", py:"Y",
 desc:"参见EOG。眼球运动和眨眼在EEG中产生的干扰。幅值100-5000μV，主要影响前额电极(Fp1/Fp2)。ICA是最有效的去除方法。"},
{term:"卡尔曼滤波", en:"Kalman Filter", cat:"算法", py:"K",
 desc:"递归最优状态估计算法。在BCI中用于：在线平滑解码输出(降低抖动)、运动轨迹预测、自适应校准。嵌入式实现：只需存储状态向量和协方差矩阵（2×2矩阵仅需16字节），计算量O(n²)可实时。"},
{term:"电化学噪声", en:"Electrochemical Noise", cat:"概念", py:"D",
 desc:"电极-组织界面的氧化还原反应产生的随机电信号。幅值10-100μV，低频(<10Hz)主导。通过稳定电极-组织界面（保持导电膏湿润、压力恒定）来抑制。"},
{term:"MISRA-C", en:"MISRA C", cat:"软件", py:"M",
 desc:"汽车工业软件可靠性协会C语言规范。医疗设备固件开发建议遵循MISRA-C 2012。使用PC-lint Plus / Cppcheck等静态分析工具检查合规性。IEC 62304要求医疗软件符合编码规范。"},
{term:"IEC 60601", en:"IEC 60601-1", cat:"标准", py:"I",
 desc:"医疗器械电气安全国际标准。对BCI最关键的要求：患者辅助电流<100μA(BF型)、1500VAC耐压、单一故障安全、外壳温升限制(植入体<1°C)。"},{term:"ISO 13485", en:"ISO 13485", cat:"标准", py:"I",
 desc:"医疗器械质量管理体系国际标准。要求：设计输入→设计输出→设计验证→设计确认→设计变更的完整追溯链。BCI产品化必须通过此认证。"},
{term:"NMPA", en:"National Medical Products Administration", cat:"标准", py:"N",
 desc:"中国国家药品监督管理局。负责医疗器械注册审批。博睿康NEO于2026年3月13日获NMPA注册证，成为全球首个获批的侵入式BCI产品。2026年政府工作报告首次将BCI列为六大未来产业之一。"},
{term:"FDA", en:"U.S. Food and Drug Administration", cat:"标准", py:"F",
 desc:"美国食品药品监督管理局。Neuralink和Synchron正在进行FDA临床试验(IDE阶段)。2026年Neuralink Blindsight获FDA突破性设备认定，可加速审批流程。"},
{term:"脑网络", en:"Brain Network (Connectome)", cat:"概念", py:"N",
 desc:"将大脑建模为图（节点=脑区/电极，边=功能连接）。关键指标：聚类系数（局部效率）、路径长度（全局效率）、小世界系数（健康大脑标志）、模块性（功能分离）。脑网络特征在BCI中可将准确率从70-85%提升到85-92%。"}
];
