const HARDWARE = [
{name:"NeuroSky MindWave", price:399, priceStr:"¥399", channels:1, sampleRate:"512Hz", interface:"BLE", type:"非侵入式", level:"入门", use:["专注度检测","α波反馈训练"], electrode:"干电极(前额)", battery:"AAA电池,8h", pros:"最便宜即开即用；专注度算法成熟", cons:"单通道信号质量差；不适合科研"},
{name:"Muse 2", price:1800, priceStr:"¥1,800", channels:4, sampleRate:"256Hz", interface:"BLE 4.2", type:"非侵入式", level:"消费级", use:["α波神经反馈","冥想训练","睡眠监测"], electrode:"干电极(TP9/AF7/AF8/TP10)", battery:"锂电池,~5h", pros:"性价比最高完整EEG；即开即用；Python SDK(muselsl)", cons:"API不如OpenBCI开放；通道数少"},
{name:"OpenBCI Ganglion", price:2500, priceStr:"¥2,500", channels:4, sampleRate:"200Hz", interface:"BLE 4.2", type:"非侵入式", level:"进阶", use:["EEG采集入门","可穿戴原型"], electrode:"任意EEG电极(10-20系统)", battery:"纽扣电池CR2032,>24h", pros:"超低功耗；开源固件；钮扣电池供电", cons:"4通道有限；采样率200Hz偏低"},
{name:"OpenBCI Cyton", price:3600, priceStr:"¥3,600", channels:8, sampleRate:"250/500/1000Hz", interface:"BLE/USB双模", type:"非侵入式", level:"研究级", use:["科研BCI","8通道EEG实验"], electrode:"任意EEG电极(10-20)", battery:"锂电池,~6h", pros:"开源生态最大；SDK完善；社区活跃", cons:"PIC32 MCU不如ARM DSP能力强；价格较高"},
{name:"OpenBCI Cyton+Daisy", price:5800, priceStr:"¥5,800", channels:16, sampleRate:"250/500/1000Hz", interface:"BLE/USB双模", type:"非侵入式", level:"科研级", use:["高密度EEG","脑网络分析"], electrode:"任意EEG电极(10-20)", battery:"锂电池,~4h", pros:"16通道最高非侵入式配置", cons:"价格高；数据量大实时处理要求高"},
{name:"Emotiv EPOC X", price:5800, priceStr:"¥5,800", channels:14, sampleRate:"128/256Hz", interface:"BLE", type:"非侵入式", level:"消费级/科研", use:["多通道EEG","情绪识别","认知研究"], electrode:"半干电极(14个)", battery:"锂电池,~9h", pros:"14通道一站式方案；商业软件生态完善", cons:"SDK授权费；开源度低；采样率低"},
{name:"BrainLink", price:999, priceStr:"¥999", channels:3, sampleRate:"512Hz", interface:"BLE", type:"非侵入式", level:"消费级", use:["专注度/放松度","教育游戏"], electrode:"干电极(前额)", battery:"锂电池,~6h", pros:"中国品牌中文支持好；App生态完善", cons:"通道少；不适合科研"},
{name:"博睿康 NEO", price:0, priceStr:"临床设备(咨询)", channels:128, sampleRate:"1kHz+", interface:"无线专有协议", type:"侵入式·硬膜外", level:"医疗级", use:["运动功能代偿","脑控设备","临床康复"], electrode:"硬膜外电极阵列(128ch)", battery:"无线充电", pros:"全球首个获批(NMPA)；36例临床100%响应率", cons:"仅限医疗机构使用；需手术植入"},
{name:"强脑科技 FocusCalm", price:799, priceStr:"¥799", channels:1, sampleRate:"250Hz", interface:"BLE", type:"非侵入式", level:"消费级", use:["压力检测","专注训练"], electrode:"干电极(前额)", battery:"锂电池,~8h", pros:"中国品牌；App体验好", cons:"单通道局限"},
{name:"g.tec Nautilus", price:50000, priceStr:">¥50,000", channels:32, sampleRate:"250/500Hz", interface:"WiFi+BLE", type:"非侵入式", level:"专业科研", use:["专业科研","临床研究","多模态BCI"], electrode:"主动电极(32ch)", battery:"锂电池,~6h", pros:"32通道高密度；主动电极极低噪声", cons:"价格极高；仅科研机构用"},
{name:"NeuroSky MindWave Mobile 2", price:599, priceStr:"¥599", channels:1, sampleRate:"512Hz", interface:"BLE 4.0", type:"非侵入式", level:"入门", use:["注意力训练","脑电游戏"], electrode:"干电极(前额+耳夹)", battery:"AAA电池", pros:"入门最便宜方案", cons:"单通道质量有限"},
{name:"DIY ADS1299方案", price:500, priceStr:"¥500(自制)", channels:8, sampleRate:"250-4000Hz", interface:"SPI→UART/USB", type:"非侵入式", level:"DIY/定制", use:["自建BCI实验","学习AFE设计"], electrode:"任意电极(需自配)", battery:"USB供电", pros:"最低成本的8通道研究级方案；完全可定制", cons:"需要PCB设计能力；需自写固件"}
];
